language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - echo "no dependencies to install"
before_script:
  - git config --global user.email "foo@example.com"
  - git config --global user.name "foo"
script:
  - python setup.py build
  - python setup.py test
